### PR TITLE
1134. Armstrong Number

### PR DESCRIPTION
**Pull request by ErdemT09**
This adds the first algorithm to this repository.
Here are few decisions I have made about conventions regarding this repository:
1. Source files names are in snake_case. playground.cpp started with a lower case letter, so I found this to be more suitable.
2. method and varible names besides those enforced by LeetCode are in snake_case
3. Class names are in PascalCase
4.  This might change in the future due to compatibility issues, however I preferred creating a class called Solution in the solution module. I instantiate and run this class in the main method in its file. So, just like in Python.

If there are other ideas and suggestions, we can change to them too, as we are only at the beginning.

### CODE REVIEW

**Comment by altayhunoglu** [comment]
Nicely said Erdem, thanks. 
I will also think about the conventions, and as you mentioned LeetCode will guide us through compatibility.

**Review by altayhunoglu — APPROVED** [review]
Great code Erdem. Thanks.

image

**Comment by ErdemT09** [comment]
I will also add a few more questions here for the sake of language practice and algorithms re-study.

**Comment by altayhunoglu** [comment]
It would be great. I will join you asap.

**Pull request merged**
